/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaexercicio13;

import javax.swing.DefaultListModel;

/**
 *
 * @author Matheus Bezerra
 */
public class telaexercicio13 extends javax.swing.JFrame {

    /**
     * Creates new form telaexercicio13
     */
    public telaexercicio13() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sliinicio = new javax.swing.JSlider();
        slifim = new javax.swing.JSlider();
        slipasso = new javax.swing.JSlider();
        lblinicio = new javax.swing.JLabel();
        lblfim = new javax.swing.JLabel();
        lblpasso = new javax.swing.JLabel();
        btncont = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstcont = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Inicio");

        jLabel2.setText("Fim");

        jLabel3.setText("Passo");

        sliinicio.setMaximum(5);
        sliinicio.setToolTipText("");
        sliinicio.setValue(0);
        sliinicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliinicioStateChanged(evt);
            }
        });

        slifim.setMaximum(20);
        slifim.setMinimum(6);
        slifim.setValue(6);
        slifim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slifimStateChanged(evt);
            }
        });

        slipasso.setMaximum(4);
        slipasso.setMinimum(1);
        slipasso.setValue(1);
        slipasso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slipassoStateChanged(evt);
            }
        });

        lblinicio.setText("0");

        lblfim.setText("6");

        lblpasso.setText("1");

        btncont.setText("Contar");
        btncont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstcont);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncont)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sliinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblinicio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slifim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblfim))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slipasso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblpasso)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(sliinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblinicio))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblfim))))
                            .addComponent(slifim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(slipasso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpasso))
                        .addGap(26, 26, 26)
                        .addComponent(btncont)
                        .addGap(0, 143, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliinicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliinicioStateChanged
        // TODO add your handling code here:
        int i = sliinicio.getValue();
        lblinicio.setText(Integer.toString(i));
    }//GEN-LAST:event_sliinicioStateChanged

    private void slifimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slifimStateChanged
        // TODO add your handling code here:
        int f = slifim.getValue();
        lblfim.setText(Integer.toString(f));
    }//GEN-LAST:event_slifimStateChanged

    private void slipassoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slipassoStateChanged
        // TODO add your handling code here:
        int p = slipasso.getValue();
        lblpasso.setText(Integer.toString(p));
    }//GEN-LAST:event_slipassoStateChanged

    private void btncontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontActionPerformed
        // TODO add your handling code here:
        int i = sliinicio.getValue();
        int f = slifim.getValue();
        int p = slipasso.getValue();
        
        DefaultListModel lista = new DefaultListModel();
        
        for(int c = i; c <= f; c += p){
            lista.addElement(c);
        }
        lstcont.setModel(lista);
    }//GEN-LAST:event_btncontActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaexercicio13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaexercicio13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaexercicio13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaexercicio13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaexercicio13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncont;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfim;
    private javax.swing.JLabel lblinicio;
    private javax.swing.JLabel lblpasso;
    private javax.swing.JList<String> lstcont;
    private javax.swing.JSlider slifim;
    private javax.swing.JSlider sliinicio;
    private javax.swing.JSlider slipasso;
    // End of variables declaration//GEN-END:variables
}
